
name: build

on:
  push:
    branches: [ "master","preparation" ]
  pull_request:
    branches: [ "master","preparation" ]

jobs:
  semgrep:
 
    name: semgrep
    runs-on: ubuntu-latest
    container:
         image: returntocorp/semgrep
    steps:
     
      - name: Upload SARIF file
        uses: actions/checkout@v3
      - name: Semgrep
        run: semrep ci --config=auto --sarif  --output=semgrep.sarif || true
      - name: Upload    
        uses: github/codeql-action/upload-sarif@v2
         with:
            sarif_file: semgrep.sarif
               if: always()
